# Generated by Django 4.1.3 on 2022-11-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id_class', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(db_column='class_name', max_length=50)),
            ],
            options={
                'db_table': 'classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id_text', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'texts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id_word', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'words',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TextsClasses',
            fields=[
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='reviews.texts')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviews.classes')),
            ],
            options={
                'db_table': 'texts_classes',
                'managed': True,
                'unique_together': {('text_id', 'class_id')},
            },
        ),
        migrations.AddField(
            model_name='texts',
            name='classes',
            field=models.ManyToManyField(through='reviews.TextsClasses', to='reviews.classes'),
        ),
        migrations.CreateModel(
            name='WordsClasses',
            fields=[
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='reviews.words')),
                ('vector', models.FloatField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviews.classes')),
            ],
            options={
                'db_table': 'words_classes',
                'managed': True,
                'unique_together': {('word_id', 'class_id')},
            },
        ),
        migrations.CreateModel(
            name='TextsWords',
            fields=[
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='reviews.texts')),
                ('tfidf', models.FloatField()),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviews.words')),
            ],
            options={
                'db_table': 'texts_words',
                'managed': True,
                'unique_together': {('text_id', 'word_id')},
            },
        ),
    ]
